yuki:
  name: 'Yuki 管理系统'
  authors: 'ShiXin,Yuki'
  version: '0.0.1'
  file-root-path: 'E:\Code\Java\Yuki\path'
  captchaType: 'digital'
spring:
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  redis:
    timeout: 10s
  messages:
    basename: i18n/messages
  profiles:
    active: dev
token:
  algorithm: HS256
  header: Authorization
  secret: y9xfuDtynPrgf585
  expireTime: 30