yuki:
  name: 'Yuki 管理系统'
  authors: 'ShiXin,Yuki'
  version: '0.0.1'
  fileRootPath: 'E:\Code\Java\Yuki\path'
  captchaType: 'digital'
spring:
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    timeout: 10s
  data:
    redis:
      repositories:
        enabled: false
  messages:
    basename: i18n/admin_messages,i18n/common_messages,i18n/framework_messages
  profiles:
    active: dev
token:
  algorithm: HS256
  header: Authorization
  secret: 094d471e2bcfe84c771b05d0e68d3aae2037d4e7c2eb218776a4a9d66add3d20
  expireTime: 30